-- =========================================
-- SOSORUN Postgres init script
-- - 컨테이너가 "처음 생성될 때만" 1회 실행됩니다.
-- - 여기에는 테이블 생성 SQL 등을 나중에 추가하면 됩니다.
-- =========================================

-- 예시(지금은 아무 것도 안 만들어도 OK)
-- CREATE TABLE IF NOT EXISTS sample (
--   id SERIAL PRIMARY KEY,
--   name TEXT NOT NULL
-- );
